#!/bin/bash
while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        echo "Master ref received. Deploying master branch to production..."
        cd /home/vooot/apps/api.vooot.nl/
        rm -rf ./live
        mkdir .live
        git --work-tree=/home/vooot/apps/api.vooot.nl/live --git-dir=/home/vooot/apps/api.vooot.nl/repo checkout -f
        cp /home/vooot/apps/api.vooot.nl/config/pm2.json ./pm2.js
        cd live
        ls -la
      	npm install
      	pm2 start pm2.json
      	echo "done."

    else
        echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
    fi
done
