#!/bin/bash
while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        echo "Master ref received. Deploying master branch to production..."
        git --work-tree=/var/www/vooot/api --git-dir=/var/git/vooot/api/.git checkout -f
      	cd /var/www/vooot/api
        ls -la
      	cp /home/admin/config/vooot/api/local.js ./config/local.js
      	npm install
      	pm2 start pm2.json
      	echo "done."

    else
        echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
    fi
done
