#!/bin/bash
while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        echo "Master ref received. Deploying master branch to production..."
        rm -rf /var/www/vooot/production
        mkdir /var/www/vooot/production
        echo "Work directory cleaned."
        git --work-tree=/var/www/vooot/production --git-dir=/var/www/vooot/repository/vooot.git checkout -f
        echo "Repository checked out to production folder."
        cd /var/www/vooot/production
        cp /var/www/vooot/config/pm2-production.json /var/www/vooot/production/backend/pm2/pm2.json
        echo "PM2 configuration file copied."
        ls -la
        echo "Installing node dependencies"
        cd /var/www/vooot/production/backend
        npm install
        echo "NPM modules installed"
        echo "Starting PM2"
        cd /var/www/vooot/production
        pm2 start /var/www/vooot/production/backend/pm2.json
        echo "Done updating the backend."

        cd /var/www/vooot/production/frontend
        npm install
        ng build --prod

    else
        echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
    fi
done
